

instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)
instance_create_layer(x,y,layer,Partical_OBJ)